---
before_install:
  - sudo apt-get update && apt-get install -y build-essential
  - sudo apt-get bc nasm autoconf libtool zlib1g-dev pkg-config curl
  - chmod +x $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/*.sh

# Language selection
language: cpp

# Compiler selection
compiler: gcc

# We may change the build prefix so we don't have to have the previlige
install:
  - sudo $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/install_openssl.sh
  - sudo $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/install_libvpx.sh
  - sudo $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/install_libopus.sh
  - sudo $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/install_libsrtp.sh
  - sudo $TRAVIS_BUILD_DIR/Docker/ubuntu/ome_base/install_ffmpeg.sh

# build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make