ifneq ($(strip $(BUILD_C_DEPEND_FILES)),)
$(BUILD_C_DEPEND_FILES) : $(BUILD_OBJECTS_DIRECTORY)/%.P : $(BUILD_PROJECTS_DIRECTORY)/%$(CONFIG_C_EXTENSION)
$(BUILD_C_OBJECT_FILES) : %.o : %.P
-include $(BUILD_C_DEPEND_FILES)
endif

ifneq ($(strip $(BUILD_CXX_DEPEND_FILES)),)
$(BUILD_CXX_DEPEND_FILES) : $(BUILD_OBJECTS_DIRECTORY)/%.P : $(BUILD_PROJECTS_DIRECTORY)/%$(CONFIG_CXX_EXTENSION)
$(BUILD_CXX_OBJECT_FILES) : %.o : %.P
-include $(BUILD_CXX_DEPEND_FILES)
endif

