BUILD_TYPE := shared

LOCAL_CFLAGS += -fPIC
LOCAL_CXXFLAGS += -fPIC

include $(PREPARE_TO_BUILD)

$(BUILD_TARGET_WITH_PATH) : $(BUILD_SHARED_LIBRARIES_WITH_PATH) $(BUILD_C_HEADER_FILES) $(BUILD_CXX_HEADER_FILES)
$(BUILD_TARGET_WITH_PATH) : $(BUILD_C_OBJECT_FILES) $(BUILD_CXX_OBJECT_FILES) $(BUILD_STATIC_LIBRARIES_WITH_PATH)
	@$(TARGET_COUNTER)
	@echo $(CURRENT_PROGRESS)"$(CONFIG_BUILD_TYPE_COLOR)[$(PRIVATE_BUILD_TYPE)]$(ANSI_RESET) Linking $(CONFIG_BUILDING_COLOR)$(PRIVATE_TARGET)$(ANSI_RESET)... => $(CONFIG_TARGET_FILE_COLOR)$@$(ANSI_RESET)"$(INCREASE_COUNT)
	@$(PRIVATE_LD) -shared -Wl,-soname,$(PRIVATE_TARGET) $(PRIVATE_LDFLAGS) -o $@ \
		$(PRIVATE_C_OBJECT_FILES) $(PRIVATE_CXX_OBJECT_FILES) $(PRIVATE_STATIC_LIBRARIES_WITH_PATH)
	@$(BUILD_STRIP)

include $(BUILD_OBJECTS)
include $(BUILD_DEPENDENCY)
