LOCAL_PATH := $(call get_local_path)
include $(DEFAULT_VARIABLES)

LOCAL_TARGET := monitoring

LOCAL_SOURCE_FILES := $(LOCAL_SOURCE_FILES)
LOCAL_HEADER_FILES := $(LOCAL_HEADER_FILES)

include $(BUILD_STATIC_LIBRARY)